; ──────────────────────────────────────────────────────────────
; PlatformIO - ESP32 Receptor (RX)
; Recibe señal cruda por UART2, aplica FIR+IIR, envía a MATLAB
; ──────────────────────────────────────────────────────────────

[env:esp32_rx]
platform = espressif32
board    = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -O2                      ; Optimización de velocidad (crítico para FIR de 201 taps)
    -DCORE_DEBUG_LEVEL=0     ; Silenciar logs del SDK que corrompen la salida binaria
