%ESCENARIOS_PRUEBA Ejecuta casos del agente experto listos para el informe.

escenarios = [
    struct('nombre', 'A ECG', 'caso', 'A', 'senal', 'Medica / biomedica', ...
        'mcu', 'ESP32', 'fs', 500, 'ram_kb', 320, 'flash_kb', 4096, ...
        'mips', 240, 'fase_lineal', true, 'nivel_ruido', 'Alto', ...
        'latencia', 'Media', 'pendiente', 'Estrecha')
    struct('nombre', 'H corriente Arduino', 'caso', 'H', 'senal', 'Corriente electrica', ...
        'mcu', 'Arduino Uno', 'fs', 2000, 'ram_kb', 2, 'flash_kb', 32, ...
        'mips', 16, 'fase_lineal', false, 'nivel_ruido', 'Medio', ...
        'latencia', 'Baja', 'pendiente', 'Estrecha')
    struct('nombre', 'J glucosa/SpO2', 'caso', 'J', 'senal', 'Medica / biomedica', ...
        'mcu', 'ESP32', 'fs', 10, 'ram_kb', 320, 'flash_kb', 4096, ...
        'mips', 240, 'fase_lineal', true, 'nivel_ruido', 'Medio', ...
        'latencia', 'Media', 'pendiente', 'Amplia')
];

fprintf('\n%-20s %-12s %7s %8s %8s %8s %-6s %-11s %-22s %10s\n', ...
    'Escenario', 'MCU', 'fs', 'RAM', 'Flash', 'MIPS', 'Fase', 'Caso', ...
    'Recomendacion', 'Confianza');
fprintf('%s\n', repmat('-', 1, 130));

for k = 1:numel(escenarios)
    e = escenarios(k);
    [tipo, ~, ~, confianza, plan] = recomendar_filtro(e.fs, e.ram_kb, e.flash_kb, ...
        e.mips, e.fase_lineal, e.nivel_ruido, e.latencia, e.pendiente, ...
        e.caso, e.senal);

    if e.fase_lineal
        faseTxt = 'Si';
    else
        faseTxt = 'No';
    end

    fprintf('%-20s %-12s %7.0f %8.1f %8.0f %8.0f %-6s %-11s %-22s %9.1f%%\n', ...
        e.nombre, e.mcu, e.fs, e.ram_kb, e.flash_kb, e.mips, faseTxt, ...
        plan.descripcion, char(tipo), confianza);
end
