; ──────────────────────────────────────────────────────────────
; PlatformIO - ESP32 Transmisor (TX)
; Lee señal del ADC y la envía al Receptor por UART2 a 10 Hz
; ──────────────────────────────────────────────────────────────

[env:esp32_tx]
platform = espressif32
board    = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600
